# Generated by Django 5.1.6 on 2025-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('workplace_type', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=255, null=True)),
                ('application_deadline', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=255, null=True)),
                ('followers_count', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_count', models.CharField(blank=True, max_length=255, null=True)),
                ('application_type', models.CharField(blank=True, max_length=255, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('job_function', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('recruiters', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
