# Generated by Django 5.1.6 on 2025-02-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_remove_joblisting_application_deadline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
